name: android-paging-coroutine

on:   
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:   
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11

        - name: Build with Gradle
          run: ./gradlew build

        - name: Build APK
          run: ./gradlew :app:assembleDebug

        - uses: actions/upload-artifact@v2
          with:
           name: Package
           path: app/build/outputs/apk/debug/
